# Generated by Django 6.1.1 on 2026-09-25 16:30

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Exactly as the prospectus prints it.", max_length=120
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Diploma", "Diploma"),
                            ("Certificate", "Certificate"),
                            ("PG Diploma", "Pg Diploma"),
                            ("Professional Diploma", "Professional Diploma"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Programming", "Programming"),
                            ("Accounting", "Accounting"),
                            ("Design", "Design"),
                            ("Web Designing", "Web Designing"),
                            ("Computer Basics", "Computer Basics"),
                            ("Multimedia", "Multimedia"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(help_text='As printed: "6 Months", "1 Year".', max_length=30),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("monthly_fee", models.PositiveIntegerField(help_text="Rupees per month.")),
                (
                    "first_month_fee",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="One or two sentences for course cards."),
                ),
                ("syllabus", models.JSONField(validators=[website.models.validate_syllabus])),
                ("image", models.ImageField(blank=True, upload_to="courses/")),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on the home page."),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, help_text='"Most enrolled", "Flagship"…', max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Published", "Published"), ("Draft", "Draft")],
                        default="Draft",
                        max_length=10,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(blank=True, help_text='"Mon–Fri, 10–11 AM"', max_length=80),
                ),
                (
                    "next_batch_start",
                    models.CharField(
                        blank=True, help_text='Text, so "Every Monday" works too.', max_length=40
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, help_text="Lower comes first."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["status", "order"], name="website_cou_status_236fed_idx")
                ],
            },
        ),
    ]
