# Generated by Django 6.1.1 on 2026-09-25 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, validators=[django.core.validators.MinLengthValidator(2)]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField(max_length=2000)),
                ("handled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["handled", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hero_headline",
                    models.CharField(default="Learn the tools. Build the work.", max_length=80),
                ),
                (
                    "hero_sub",
                    models.TextField(
                        default="An ISO 9001:2000 certified multimedia institute in Nehru Nagar, Kanpur — computer, accounting, design and animation courses taught on real machines, from typing to an eighteen-month multimedia diploma."
                    ),
                ),
                (
                    "stat_students",
                    models.CharField(
                        default="500+", max_length=12, verbose_name="Students trained"
                    ),
                ),
                (
                    "stat_courses",
                    models.CharField(default="9", max_length=12, verbose_name="Courses offered"),
                ),
                (
                    "stat_years",
                    models.CharField(default="9+", max_length=12, verbose_name="Years of teaching"),
                ),
                (
                    "stat_certificates",
                    models.CharField(
                        default="1000+", max_length=12, verbose_name="Certificates issued"
                    ),
                ),
                (
                    "show_stats",
                    models.BooleanField(
                        default=True, help_text="Show the numbers band on the home page."
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        default="Animation Academy is run by IOCSGT Computer Education at 107/235 Nehru Nagar, Kanpur. Small batches, a machine for every student, and certificates carrying a verifiable ID."
                    ),
                ),
                (
                    "phones",
                    models.CharField(
                        default="8707447880, 9336202125",
                        help_text="Comma-separated, first is main.",
                        max_length=80,
                    ),
                ),
                ("email", models.EmailField(default="info@animationacademy.in", max_length=254)),
                (
                    "address",
                    models.CharField(
                        default="107/235 Nehru Nagar, Kanpur, Uttar Pradesh 208012", max_length=200
                    ),
                ),
                (
                    "registration_fee",
                    models.PositiveIntegerField(default=250, help_text="One-time, in rupees."),
                ),
                (
                    "director_name",
                    models.CharField(
                        blank=True, help_text="Signs the certificates (Phase 7).", max_length=80
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Off: the admission form says registration is closed.",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="On: the public site shows a maintenance page."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("text", models.CharField(help_text="One or two sentences.", max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Holiday", "Holiday"),
                            ("Course Update", "Course Update"),
                            ("Exam", "Exam"),
                            ("Event", "Event"),
                            ("Important Notice", "Important"),
                        ],
                        default="General",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The day it's about (holiday, exam, event) or posted."
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["published", "date"], name="website_ann_publish_0aa6c2_idx"
                    )
                ],
            },
        ),
    ]
