# Generated by Django 6.1.1 on 2026-09-27 09:26

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_contactmessage_sitesettings_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, storage=website.models.course_image_storage, upload_to="courses/"
            ),
        ),
    ]
