# Generated by Django 6.1.1 on 2026-09-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_course_image_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="allow_registration",
            field=models.BooleanField(
                default=True, help_text="Off: students can't request new courses from their portal."
            ),
        ),
    ]
