# Generated by Django 6.1.1 on 2026-09-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_allow_registration_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="The course they asked about, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to="website.course",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
