# Generated by Django 6.1.1 on 2026-09-25 21:43

import django.db.models.deletion
import django.utils.timezone
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0002_contactmessage_sitesettings_announcement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="In capitals, as it prints on certificates.", max_length=100
                    ),
                ),
                ("father_name", models.CharField(max_length=100, verbose_name="father's name")),
                ("mobile", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("dob", models.DateField(verbose_name="date of birth")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                        max_length=10,
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="students/photos/")),
                ("address", models.CharField(max_length=250)),
                ("pincode", models.CharField(max_length=6)),
                ("city", models.CharField(default="Kanpur", max_length=60)),
                ("state", models.CharField(default="Uttar Pradesh", max_length=60)),
                ("country", models.CharField(default="India", max_length=60)),
                (
                    "employment",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Unemployed", "Unemployed"),
                            ("Employed", "Employed"),
                            ("Self-employed", "Self Employed"),
                            ("Part-time", "Part Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        default=students.models.blank_qualifications,
                        validators=[students.models.validate_qualifications],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Graduated", "Graduated"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="E.g. why it was cancelled.", max_length=250
                    ),
                ),
                (
                    "certificate_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("certificate_issued_on", models.DateField(blank=True, null=True)),
                (
                    "certificate_issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="website.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_st_status_5e2210_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="students_en_status_c844f7_idx"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Cancelled"), _negated=True),
                fields=("student", "course"),
                name="one_live_enrollment_per_course",
                violation_error_message="This student is already enrolled in this course.",
            ),
        ),
    ]
