/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/announcements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_announcements_list"];
        put?: never;
        post: operations["admin_announcements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/announcements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_announcements_retrieve"];
        put?: never;
        post?: never;
        delete: operations["admin_announcements_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_announcements_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/certificates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_certificates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/certificates/{code}/pdf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_certificates_pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contact-messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_contact_messages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contact-messages/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["admin_contact_messages_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_courses_list"];
        put?: never;
        post: operations["admin_courses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_courses_retrieve"];
        put?: never;
        post?: never;
        delete: operations["admin_courses_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_courses_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/courses/{slug}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload (multipart `image`) or remove (`image: null`) a course's artwork. */
        post: operations["admin_courses_image_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/enrollments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_enrollments_list"];
        put?: never;
        post: operations["admin_enrollments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/enrollments/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_enrollments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/enrollments/{code}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Pending → Active. A pending student becomes Active too. */
        post: operations["admin_enrollments_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/enrollments/{code}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Active → Completed, and the certificate is issued. */
        post: operations["admin_enrollments_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/enrollments/{code}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Pending or Active → Cancelled (a rejected admission, or a student who left). */
        post: operations["admin_enrollments_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/site/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_site_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["admin_site_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_students_list"];
        put?: never;
        post: operations["admin_students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/students/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_students_retrieve"];
        put?: never;
        post?: never;
        /** @description Deactivate (records are kept): status Inactive, login blocked, signed out. */
        delete: operations["admin_students_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_students_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/students/{code}/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_students_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/announcements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Published announcements as a notice board orders them: upcoming (today onwards) soonest
         *     first, then past ones newest first. `upcoming=true` keeps only upcoming holidays and events.
         */
        get: operations["announcements_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Changes the password, signs out every other session and starts a new one here. */
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description No request authentication, but failures are still 401 (with a Bearer challenge), not 403. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Works even when the access token has expired: it only needs the refresh cookie. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description No request authentication, but failures are still 401 (with a Bearer challenge), not 403. */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public endpoints: no authentication, so a stale token can never turn them into a 401. */
        post: operations["contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published courses. The catalogue is small, so it's one unpaginated list. */
        get: operations["courses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public endpoints: no authentication, so a stale token can never turn them into a 401. */
        get: operations["courses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every category, with how many published courses it has (for the filter chips). */
        get: operations["courses_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/certificates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_certificates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/certificates/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_certificates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/certificates/{code}/pdf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_certificates_pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/enrollments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_enrollments_list"];
        put?: never;
        post: operations["me_enrollments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/site/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public endpoints: no authentication, so a stale token can never turn them into a 401. */
        get: operations["site_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public check of a certificate ID. Shows only the name, course, duration and date. */
        get: operations["verify_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response of login and refresh. The refresh token travels only in the httpOnly cookie. */
        AccessToken: {
            access: string;
            user: components["schemas"]["User"];
        };
        AdminAnnouncement: {
            readonly id: number;
            title: string;
            /** @description One or two sentences. */
            text: string;
            category?: components["schemas"]["AnnouncementCategoryEnum"];
            /**
             * Format: date
             * @description The day it's about (holiday, exam, event) or posted.
             */
            date: string;
            published?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AdminAnnouncementRequest: {
            title: string;
            /** @description One or two sentences. */
            text: string;
            category?: components["schemas"]["AnnouncementCategoryEnum"];
            /**
             * Format: date
             * @description The day it's about (holiday, exam, event) or posted.
             */
            date: string;
            published?: boolean;
        };
        AdminCertificate: {
            code: string;
            /** Format: date */
            issued_on: string;
            student: components["schemas"]["AdminStudentRef"];
            course: components["schemas"]["AdminCourseRef"];
            /** @default  */
            issued_by: string | null;
        };
        AdminContactMessage: {
            readonly id: number;
            readonly name: string;
            readonly phone: string;
            /** Format: email */
            readonly email: string;
            readonly course: string;
            readonly message: string;
            handled?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        AdminCourse: {
            slug?: string;
            /** @description Exactly as the prospectus prints it. */
            name: string;
            kind: components["schemas"]["KindEnum"];
            category: components["schemas"]["CourseCategoryEnum"];
            level?: components["schemas"]["LevelEnum"];
            status?: components["schemas"]["CourseStatusEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            duration_label: string;
            months: number;
            /** @description Rupees per month. */
            monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            first_month_fee?: number | null;
            readonly total_fee: number;
            /** @description One or two sentences for course cards. */
            description: string;
            syllabus: components["schemas"]["SyllabusGroupInput"][];
            /** Format: uri */
            readonly image: string | null;
            /** @description Show on the home page. */
            featured?: boolean;
            /** @description "Most enrolled", "Flagship"… */
            tag?: string;
            /** @description "Mon–Fri, 10–11 AM" */
            schedule?: string;
            /** @description Text, so "Every Monday" works too. */
            next_batch_start?: string;
            /** @description Lower comes first. */
            order?: number;
            readonly enrollment_count: number;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AdminCourseRef: {
            readonly slug: string;
            /** @description Exactly as the prospectus prints it. */
            readonly name: string;
            readonly kind: components["schemas"]["KindEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            readonly duration_label: string;
            readonly months: number;
            /** @description Rupees per month. */
            readonly monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            readonly first_month_fee: number | null;
        };
        AdminCourseRequest: {
            slug?: string;
            /** @description Exactly as the prospectus prints it. */
            name: string;
            kind: components["schemas"]["KindEnum"];
            category: components["schemas"]["CourseCategoryEnum"];
            level?: components["schemas"]["LevelEnum"];
            status?: components["schemas"]["CourseStatusEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            duration_label: string;
            months: number;
            /** @description Rupees per month. */
            monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            first_month_fee?: number | null;
            /** @description One or two sentences for course cards. */
            description: string;
            syllabus: components["schemas"]["SyllabusGroupInputRequest"][];
            /** @description Show on the home page. */
            featured?: boolean;
            /** @description "Most enrolled", "Flagship"… */
            tag?: string;
            /** @description "Mon–Fri, 10–11 AM" */
            schedule?: string;
            /** @description Text, so "Every Monday" works too. */
            next_batch_start?: string;
            /** @description Lower comes first. */
            order?: number;
        };
        AdminDashboard: {
            counts: components["schemas"]["AdminDashboardCounts"];
            /** @description The 5 oldest waiting. */
            pending: components["schemas"]["AdminEnrollment"][];
            recent_messages: components["schemas"]["AdminDashboardMessage"][];
            upcoming: components["schemas"]["Announcement"][];
        };
        AdminDashboardCounts: {
            /** @description Not inactive. */
            students: number;
            pending_admissions: number;
            active_enrollments: number;
            certificates: number;
            admissions_this_month: number;
            unhandled_messages: number;
        };
        AdminDashboardMessage: {
            id: number;
            name: string;
            phone: string;
            message: string;
            /** Format: date-time */
            created_at: string;
        };
        AdminEnrollment: {
            readonly code: string;
            /** @default Pending */
            readonly status: components["schemas"]["EnrollmentStatusEnum"];
            readonly student: components["schemas"]["AdminStudentRef"];
            readonly course: components["schemas"]["AdminCourseRef"];
            /** Format: date-time */
            readonly applied_at: string;
            /** Format: date-time */
            readonly approved_at: string | null;
            /** Format: date-time */
            readonly completed_at: string | null;
            /** @description E.g. why it was cancelled. */
            readonly note: string;
            readonly certificate_code: string | null;
            /** Format: date */
            readonly certificate_issued_on: string | null;
        };
        /** @description The office enrolling a student in person (e.g. a walk-in who has already paid). */
        AdminEnrollmentCreateRequest: {
            student: string;
            course: string;
            /** @default Active */
            status: components["schemas"]["AdminEnrollmentCreateStatusEnum"];
        };
        /**
         * @description * `Pending` - Pending
         *     * `Active` - Active
         * @enum {string}
         */
        AdminEnrollmentCreateStatusEnum: "Pending" | "Active";
        AdminSite: {
            hero_headline?: string;
            hero_sub?: string;
            /** Students trained */
            stat_students?: string;
            /** Courses offered */
            stat_courses?: string;
            /** Years of teaching */
            stat_years?: string;
            /** Certificates issued */
            stat_certificates?: string;
            /** @description Show the numbers band on the home page. */
            show_stats?: boolean;
            about?: string;
            /** @description Comma-separated, first is main. */
            phones?: string;
            /** Format: email */
            email?: string;
            address?: string;
            /** @description One-time, in rupees. */
            registration_fee?: number;
            /** @description Signs the certificates (Phase 7). */
            director_name?: string;
            /** @description Off: students can't request new courses from their portal. */
            allow_registration?: boolean;
            /** @description On: the public site shows a maintenance page. */
            maintenance_mode?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Full record. Unlike the student's own profile, staff can change identity fields, the
         *     login email and the status (Inactive also blocks the login).
         */
        AdminStudent: {
            readonly code: string;
            status?: components["schemas"]["StudentStatusEnum"];
            /** Format: email */
            email?: string;
            /** @description In capitals, as it prints on certificates. */
            name: string;
            /** Father's name */
            father_name: string;
            /**
             * Date of birth
             * Format: date
             */
            dob: string;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            mobile?: string;
            phone?: string;
            address: string;
            pincode?: string;
            city?: string;
            state?: string;
            country?: string;
            employment: components["schemas"]["EmploymentEnum"];
            qualifications: unknown;
            /** Format: uri */
            photo?: string | null;
            /** Format: date-time */
            readonly joined_at: string;
            readonly enrollments: components["schemas"]["StudentEnrollment"][];
        };
        /** @description Adding a student at the office. A temporary password is generated and shown once. */
        AdminStudentCreateRequest: {
            name: string;
            father_name: string;
            /** Format: date */
            dob: string;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            address: string;
            pincode: string;
            /** @default Kanpur */
            city: string;
            mobile: string;
            /** @default  */
            phone: string;
            qualifications: unknown;
            /** Format: email */
            email: string;
            employment: components["schemas"]["EmploymentEnum"];
            course?: string | null;
        };
        AdminStudentCreated: {
            student: components["schemas"]["AdminStudent"];
            temporary_password: string;
        };
        AdminStudentList: {
            readonly code: string;
            /** @description In capitals, as it prints on certificates. */
            readonly name: string;
            /** Format: email */
            readonly email: string;
            readonly mobile: string;
            readonly city: string;
            readonly status: components["schemas"]["StudentStatusEnum"];
            /** Format: uri */
            readonly photo: string | null;
            /** Format: date-time */
            readonly joined_at: string;
            readonly enrollment_count: number;
        };
        AdminStudentRef: {
            readonly code: string;
            /** @description In capitals, as it prints on certificates. */
            readonly name: string;
            readonly mobile: string;
            /** Format: uri */
            readonly photo: string | null;
            readonly status: components["schemas"]["StudentStatusEnum"];
        };
        Announcement: {
            readonly id: number;
            readonly title: string;
            /** @description One or two sentences. */
            readonly text: string;
            readonly category: components["schemas"]["AnnouncementCategoryEnum"];
            /**
             * Format: date
             * @description The day it's about (holiday, exam, event) or posted.
             */
            readonly date: string;
        };
        /**
         * @description * `General` - General
         *     * `Holiday` - Holiday
         *     * `Course Update` - Course Update
         *     * `Exam` - Exam
         *     * `Event` - Event
         *     * `Important Notice` - Important
         * @enum {string}
         */
        AnnouncementCategoryEnum: "General" | "Holiday" | "Course Update" | "Exam" | "Event" | "Important Notice";
        /** @description A signed-in student applying for another course. */
        ApplyRequest: {
            course: string;
            accept_no_refund: boolean;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Category: {
            value: string;
            label: string;
            /** @description Published courses in this category. */
            count: number;
        };
        /** @description Everything printed on the certificate (from students.services.CertificateData). */
        Certificate: {
            code: string;
            student_name: string;
            course_name: string;
            course_kind: string;
            duration: string;
            /** Format: date */
            issued_on: string;
            director_name: string;
            /** Format: uri */
            verify_url: string;
        };
        CertificateList: {
            code: string;
            /** Format: date */
            issued_on: string;
            course: components["schemas"]["EnrollmentCourse"];
        };
        ChangePasswordRequest: {
            old_password: string;
            new_password: string;
        };
        /**
         * @description The website's message form: name and phone (the office calls back), plus an optional
         *     course and message.
         */
        ContactRequest: {
            name: string;
            phone: string;
            course?: string | null;
            message?: string;
            website?: string;
        };
        ContactSent: {
            detail: string;
        };
        /**
         * @description * `Programming` - Programming
         *     * `Accounting` - Accounting
         *     * `Design` - Design
         *     * `Web Designing` - Web Designing
         *     * `Computer Basics` - Computer Basics
         *     * `Multimedia` - Multimedia
         * @enum {string}
         */
        CourseCategoryEnum: "Programming" | "Accounting" | "Design" | "Web Designing" | "Computer Basics" | "Multimedia";
        /** @description Card fields for the catalogue. Fees are rupees; `total_fee` excludes registration. */
        CourseDetail: {
            readonly slug: string;
            /** @description Exactly as the prospectus prints it. */
            readonly name: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly category: components["schemas"]["CourseCategoryEnum"];
            readonly level: components["schemas"]["LevelEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            readonly duration_label: string;
            readonly months: number;
            /** @description Rupees per month. */
            readonly monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            readonly first_month_fee: number | null;
            readonly total_fee: number;
            /** @description One or two sentences for course cards. */
            readonly description: string;
            /** Format: uri */
            readonly image: string | null;
            /** @description Show on the home page. */
            readonly featured: boolean;
            /** @description "Most enrolled", "Flagship"… */
            readonly tag: string;
            /** @description "Mon–Fri, 10–11 AM" */
            readonly schedule: string;
            /** @description Text, so "Every Monday" works too. */
            readonly next_batch_start: string;
            readonly syllabus: components["schemas"]["SyllabusGroup"][];
        };
        CourseImageRequest: {
            /** Format: binary */
            image: string | null;
        };
        /** @description Card fields for the catalogue. Fees are rupees; `total_fee` excludes registration. */
        CourseList: {
            readonly slug: string;
            /** @description Exactly as the prospectus prints it. */
            readonly name: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly category: components["schemas"]["CourseCategoryEnum"];
            readonly level: components["schemas"]["LevelEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            readonly duration_label: string;
            readonly months: number;
            /** @description Rupees per month. */
            readonly monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            readonly first_month_fee: number | null;
            readonly total_fee: number;
            /** @description One or two sentences for course cards. */
            readonly description: string;
            /** Format: uri */
            readonly image: string | null;
            /** @description Show on the home page. */
            readonly featured: boolean;
            /** @description "Most enrolled", "Flagship"… */
            readonly tag: string;
            /** @description "Mon–Fri, 10–11 AM" */
            readonly schedule: string;
            /** @description Text, so "Every Monday" works too. */
            readonly next_batch_start: string;
        };
        /**
         * @description * `Published` - Published
         *     * `Draft` - Draft
         * @enum {string}
         */
        CourseStatusEnum: "Published" | "Draft";
        /** @description Response shape of GET /me/dashboard/ (for the schema). */
        Dashboard: {
            counts: components["schemas"]["DashboardCounts"];
            /** @description Pending and active enrollments. */
            current: components["schemas"]["MyEnrollment"][];
            /** @description The three most recent. */
            certificates: components["schemas"]["MyEnrollment"][];
            /** @description Holidays and events from today. */
            upcoming: components["schemas"]["Announcement"][];
        };
        DashboardCounts: {
            pending: number;
            active: number;
            completed: number;
            certificates: number;
        };
        /**
         * @description * `Student` - Student
         *     * `Unemployed` - Unemployed
         *     * `Employed` - Employed
         *     * `Self-employed` - Self Employed
         *     * `Part-time` - Part Time
         * @enum {string}
         */
        EmploymentEnum: "Student" | "Unemployed" | "Employed" | "Self-employed" | "Part-time";
        EnrollmentCourse: {
            readonly slug: string;
            /** @description Exactly as the prospectus prints it. */
            readonly name: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly category: components["schemas"]["CourseCategoryEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            readonly duration_label: string;
            readonly months: number;
            /** @description Rupees per month. */
            readonly monthly_fee: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            readonly first_month_fee: number | null;
            readonly total_fee: number;
            /** @description "Mon–Fri, 10–11 AM" */
            readonly schedule: string;
            /** @description Text, so "Every Monday" works too. */
            readonly next_batch_start: string;
        };
        /**
         * @description * `Pending` - Pending
         *     * `Active` - Active
         *     * `Completed` - Completed
         *     * `Cancelled` - Cancelled
         * @enum {string}
         */
        EnrollmentStatusEnum: "Pending" | "Active" | "Completed" | "Cancelled";
        /**
         * @description * `Male` - Male
         *     * `Female` - Female
         *     * `Other` - Other
         * @enum {string}
         */
        GenderEnum: "Male" | "Female" | "Other";
        /**
         * @description * `Diploma` - Diploma
         *     * `Certificate` - Certificate
         *     * `PG Diploma` - Pg Diploma
         *     * `Professional Diploma` - Professional Diploma
         * @enum {string}
         */
        KindEnum: "Diploma" | "Certificate" | "PG Diploma" | "Professional Diploma";
        /**
         * @description * `Beginner` - Beginner
         *     * `Intermediate` - Intermediate
         *     * `Advanced` - Advanced
         * @enum {string}
         */
        LevelEnum: "Beginner" | "Intermediate" | "Advanced";
        /** @description Email + password → access and refresh tokens carrying the user's role and name. */
        LoginRequest: {
            email: string;
            password: string;
        };
        MyEnrollment: {
            readonly code: string;
            readonly status: components["schemas"]["EnrollmentStatusEnum"];
            readonly course: components["schemas"]["EnrollmentCourse"];
            /** Format: date-time */
            readonly applied_at: string;
            /** Format: date-time */
            readonly approved_at: string | null;
            /** Format: date-time */
            readonly completed_at: string | null;
            readonly certificate_code: string | null;
            /** Format: date */
            readonly certificate_issued_on: string | null;
        };
        PaginatedAdminAnnouncementList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminAnnouncement"][];
        };
        PaginatedAdminCertificateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminCertificate"][];
        };
        PaginatedAdminContactMessageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminContactMessage"][];
        };
        PaginatedAdminEnrollmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminEnrollment"][];
        };
        PaginatedAdminStudentListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminStudentList"][];
        };
        PasswordChanged: {
            access: string;
        };
        PatchedAdminAnnouncementRequest: {
            title?: string;
            /** @description One or two sentences. */
            text?: string;
            category?: components["schemas"]["AnnouncementCategoryEnum"];
            /**
             * Format: date
             * @description The day it's about (holiday, exam, event) or posted.
             */
            date?: string;
            published?: boolean;
        };
        PatchedAdminContactMessageRequest: {
            handled?: boolean;
        };
        PatchedAdminCourseRequest: {
            slug?: string;
            /** @description Exactly as the prospectus prints it. */
            name?: string;
            kind?: components["schemas"]["KindEnum"];
            category?: components["schemas"]["CourseCategoryEnum"];
            level?: components["schemas"]["LevelEnum"];
            status?: components["schemas"]["CourseStatusEnum"];
            /** @description As printed: "6 Months", "1 Year". */
            duration_label?: string;
            months?: number;
            /** @description Rupees per month. */
            monthly_fee?: number;
            /** @description Only if the first month costs more (PDM: ₹4,000, then ₹3,000 × 17). */
            first_month_fee?: number | null;
            /** @description One or two sentences for course cards. */
            description?: string;
            syllabus?: components["schemas"]["SyllabusGroupInputRequest"][];
            /** @description Show on the home page. */
            featured?: boolean;
            /** @description "Most enrolled", "Flagship"… */
            tag?: string;
            /** @description "Mon–Fri, 10–11 AM" */
            schedule?: string;
            /** @description Text, so "Every Monday" works too. */
            next_batch_start?: string;
            /** @description Lower comes first. */
            order?: number;
        };
        PatchedAdminSiteRequest: {
            hero_headline?: string;
            hero_sub?: string;
            /** Students trained */
            stat_students?: string;
            /** Courses offered */
            stat_courses?: string;
            /** Years of teaching */
            stat_years?: string;
            /** Certificates issued */
            stat_certificates?: string;
            /** @description Show the numbers band on the home page. */
            show_stats?: boolean;
            about?: string;
            /** @description Comma-separated, first is main. */
            phones?: string;
            /** Format: email */
            email?: string;
            address?: string;
            /** @description One-time, in rupees. */
            registration_fee?: number;
            /** @description Signs the certificates (Phase 7). */
            director_name?: string;
            /** @description Off: students can't request new courses from their portal. */
            allow_registration?: boolean;
            /** @description On: the public site shows a maintenance page. */
            maintenance_mode?: boolean;
        };
        /**
         * @description Full record. Unlike the student's own profile, staff can change identity fields, the
         *     login email and the status (Inactive also blocks the login).
         */
        PatchedAdminStudentRequest: {
            status?: components["schemas"]["StudentStatusEnum"];
            /** Format: email */
            email?: string;
            /** @description In capitals, as it prints on certificates. */
            name?: string;
            /** Father's name */
            father_name?: string;
            /**
             * Date of birth
             * Format: date
             */
            dob?: string;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            mobile?: string;
            phone?: string;
            address?: string;
            pincode?: string;
            city?: string;
            state?: string;
            country?: string;
            employment?: components["schemas"]["EmploymentEnum"];
            qualifications?: unknown;
            /** Format: binary */
            photo?: string | null;
        };
        /**
         * @description What a student sees and edits. Identity (name, father's name, date of birth), the code and
         *     the status are read-only: the office changes those, because they print on certificates.
         */
        PatchedProfileRequest: {
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            mobile?: string;
            phone?: string;
            address?: string;
            pincode?: string;
            city?: string;
            state?: string;
            country?: string;
            employment?: components["schemas"]["EmploymentEnum"];
            qualifications?: unknown;
            /** Format: binary */
            photo?: string | null;
        };
        /**
         * @description What a student sees and edits. Identity (name, father's name, date of birth), the code and
         *     the status are read-only: the office changes those, because they print on certificates.
         */
        Profile: {
            readonly code: string;
            readonly status: components["schemas"]["StudentStatusEnum"];
            /** Format: email */
            readonly email: string;
            /** @description In capitals, as it prints on certificates. */
            readonly name: string;
            /** Father's name */
            readonly father_name: string;
            /**
             * Date of birth
             * Format: date
             */
            readonly dob: string;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            mobile?: string;
            phone?: string;
            address: string;
            pincode?: string;
            city?: string;
            state?: string;
            country?: string;
            employment: components["schemas"]["EmploymentEnum"];
            qualifications: unknown;
            /** Format: uri */
            photo?: string | null;
            /** Format: date-time */
            readonly joined_at: string;
        };
        RejectRequest: {
            /** @default  */
            reason: string;
        };
        /**
         * @description * `student` - Student
         *     * `admin` - Admin
         * @enum {string}
         */
        RoleEnum: "student" | "admin";
        /** @description Public institute details and homepage text. */
        Site: {
            readonly hero_headline: string;
            readonly hero_sub: string;
            readonly stats: components["schemas"]["Stat"][];
            readonly about: string;
            readonly phones: string[];
            /** Format: email */
            readonly email: string;
            readonly address: string;
            /** @description One-time, in rupees. */
            readonly registration_fee: number;
            /** @description Off: students can't request new courses from their portal. */
            readonly allow_registration: boolean;
            /** @description On: the public site shows a maintenance page. */
            readonly maintenance_mode: boolean;
        };
        Stat: {
            /** @description As the office typed it: "500+". */
            value: string;
            label: string;
        };
        StudentEnrollment: {
            code: string;
            status: string;
            course: components["schemas"]["StudentEnrollmentCourse"];
            /** Format: date-time */
            applied_at: string;
            certificate_code: string | null;
        };
        StudentEnrollmentCourse: {
            slug: string;
            name: string;
        };
        /**
         * @description * `Pending` - Pending
         *     * `Active` - Active
         *     * `Inactive` - Inactive
         *     * `Graduated` - Graduated
         * @enum {string}
         */
        StudentStatusEnum: "Pending" | "Active" | "Inactive" | "Graduated";
        SyllabusGroup: {
            title: string;
            duration: string;
            tools: string;
            items: string[];
        };
        SyllabusGroupInput: {
            /** @default  */
            title: string;
            /** @default  */
            duration: string;
            /** @default  */
            tools: string;
            items: string[];
        };
        SyllabusGroupInputRequest: {
            /** @default  */
            title: string;
            /** @default  */
            duration: string;
            /** @default  */
            tools: string;
            items: string[];
        };
        TemporaryPassword: {
            temporary_password: string;
        };
        User: {
            /** Format: email */
            readonly email: string;
            readonly name: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly student_code: string | null;
        };
        /** @description What the public verify page may show: no contact or personal details beyond the name. */
        Verification: {
            valid: boolean;
            code: string;
            student_name: string;
            course_name: string;
            duration: string;
            /** Format: date */
            issued_on: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_announcements_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                published?: boolean;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminAnnouncementList"];
                };
            };
        };
    };
    admin_announcements_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAnnouncementRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminAnnouncementRequest"];
                "multipart/form-data": components["schemas"]["AdminAnnouncementRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnnouncement"];
                };
            };
        };
    };
    admin_announcements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnnouncement"];
                };
            };
        };
    };
    admin_announcements_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_announcements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminAnnouncementRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminAnnouncementRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminAnnouncementRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAnnouncement"];
                };
            };
        };
    };
    admin_certificates_list: {
        parameters: {
            query?: {
                /** @description Course slug */
                course?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Certificate code, student name or code */
                q?: string;
                /** @description A search term. */
                search?: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminCertificateList"];
                };
            };
        };
    };
    admin_certificates_pdf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    admin_contact_messages_list: {
        parameters: {
            query?: {
                handled?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminContactMessageList"];
                };
            };
        };
    };
    admin_contact_messages_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminContactMessageRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminContactMessageRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminContactMessageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContactMessage"];
                };
            };
        };
    };
    admin_courses_list: {
        parameters: {
            query?: {
                category?: "Accounting" | "Computer Basics" | "Design" | "Multimedia" | "Programming" | "Web Designing";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                q?: string;
                /** @description A search term. */
                search?: string;
                status?: "Draft" | "Published";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"][];
                };
            };
        };
    };
    admin_courses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminCourseRequest"];
                "multipart/form-data": components["schemas"]["AdminCourseRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"];
                };
            };
        };
    };
    admin_courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"];
                };
            };
        };
    };
    admin_courses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_courses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminCourseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminCourseRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminCourseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"];
                };
            };
        };
    };
    admin_courses_image_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CourseImageRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CourseImageRequest"];
                "application/json": components["schemas"]["CourseImageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCourse"];
                };
            };
        };
    };
    admin_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboard"];
                };
            };
        };
    };
    admin_enrollments_list: {
        parameters: {
            query?: {
                /** @description Course slug */
                course?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Student name or code, or enrollment code */
                q?: string;
                /** @description A search term. */
                search?: string;
                status?: "Active" | "Cancelled" | "Completed" | "Pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminEnrollmentList"];
                };
            };
        };
    };
    admin_enrollments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEnrollmentCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminEnrollmentCreateRequest"];
                "multipart/form-data": components["schemas"]["AdminEnrollmentCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnrollment"];
                };
            };
            /** @description Already enrolled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_enrollments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnrollment"];
                };
            };
        };
    };
    admin_enrollments_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnrollment"];
                };
            };
        };
    };
    admin_enrollments_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnrollment"];
                };
            };
        };
    };
    admin_enrollments_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RejectRequest"];
                "multipart/form-data": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnrollment"];
                };
            };
        };
    };
    admin_site_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSite"];
                };
            };
        };
    };
    admin_site_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminSiteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminSiteRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminSiteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSite"];
                };
            };
        };
    };
    admin_students_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Name, student code, mobile or email */
                q?: string;
                /** @description A search term. */
                search?: string;
                status?: "Active" | "Graduated" | "Inactive" | "Pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminStudentListList"];
                };
            };
        };
    };
    admin_students_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminStudentCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminStudentCreateRequest"];
                "multipart/form-data": components["schemas"]["AdminStudentCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStudentCreated"];
                };
            };
        };
    };
    admin_students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStudent"];
                };
            };
        };
    };
    admin_students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_students_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminStudentRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminStudentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminStudentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStudent"];
                };
            };
        };
    };
    admin_students_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"];
                };
            };
        };
    };
    announcements_list: {
        parameters: {
            query?: {
                category?: "Course Update" | "Event" | "Exam" | "General" | "Holiday" | "Important Notice";
                /** @description 1–50 */
                limit?: number;
                upcoming?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"][];
                };
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordChanged"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContactRequest"];
                "multipart/form-data": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSent"];
                };
            };
        };
    };
    courses_list: {
        parameters: {
            query?: {
                /**
                 * @description * `Programming` - Programming
                 *     * `Accounting` - Accounting
                 *     * `Design` - Design
                 *     * `Web Designing` - Web Designing
                 *     * `Computer Basics` - Computer Basics
                 *     * `Multimedia` - Multimedia
                 */
                category?: "Accounting" | "Computer Basics" | "Design" | "Multimedia" | "Programming" | "Web Designing";
                featured?: boolean;
                /**
                 * @description * `Beginner` - Beginner
                 *     * `Intermediate` - Intermediate
                 *     * `Advanced` - Advanced
                 */
                level?: "Advanced" | "Beginner" | "Intermediate";
                max_fee?: number;
                min_fee?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description Search name, description and syllabus */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseList"][];
                };
            };
        };
    };
    courses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
        };
    };
    courses_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    me_certificates_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateList"][];
                };
            };
        };
    };
    me_certificates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
        };
    };
    me_certificates_pdf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    me_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    me_enrollments_list: {
        parameters: {
            query?: {
                status?: "Active" | "Cancelled" | "Completed" | "Pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEnrollment"][];
                };
            };
        };
    };
    me_enrollments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplyRequest"];
                "multipart/form-data": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEnrollment"];
                };
            };
            /** @description Already applied for this course. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    site_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
        };
    };
    verify_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verification"];
                };
            };
            /** @description No such certificate. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
