// Generates src/styles/tokens.css from design-system/tokens.json (the single source of truth).
// Run with `npm run tokens` after the design system changes. Do not edit tokens.css by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../design-system/tokens.json");
const out = resolve(here, "../src/styles/tokens.css");
const tokens = JSON.parse(readFileSync(src, "utf8"));

const themes = tokens.color.themes.map((t) => t.id); // ["light", "dark"]
const first = themes[0];
const valueFor = (value, theme) =>
  typeof value === "string" ? value : (value[theme] ?? value[first]);

// Raw, theme-switching variables. Shadows get an `elev-` prefix so they don't collide with
// Tailwind's own --shadow-* theme variables.
const rawVars = (theme) => [
  ...tokens.color.tokens.map(
    (t) => `  --${t.name}: ${valueFor(t.value, theme)};`,
  ),
  ...tokens.shadow.tokens.map(
    (t) =>
      `  --elev-${t.name.replace(/^shadow-/, "")}: ${valueFor(t.value, theme)};`,
  ),
];

// next/font exposes each family as a CSS variable (see src/app/fonts.ts).
const fontVars = {
  Archivo: "var(--font-archivo)",
  '"Source Sans 3"': "var(--font-source-sans)",
  '"EB Garamond"': "var(--font-eb-garamond)",
  '"JetBrains Mono"': "var(--font-jetbrains-mono)",
};
const family = (stack) => {
  const [head, ...rest] = stack.split(/,\s*/);
  return [fontVars[head] ?? head, ...rest].join(", ");
};

// Responsive overrides the design system states in prose (PROJECT_GUIDE §5).
const mobile = { "display-xl": { fontSize: "38px", lineHeight: "44px" } };

const typeUtilities = tokens.type.groups.flatMap((group) =>
  group.styles.map((style) => {
    const fam = style.family ?? group.family;
    const lines = [
      `  font-family: ${family(tokens.type.families[fam])};`,
      `  font-size: ${style.fontSize};`,
      `  line-height: ${style.lineHeight};`,
      `  font-weight: ${style.fontWeight};`,
    ];
    if (style.letterSpacing)
      lines.push(`  letter-spacing: ${style.letterSpacing};`);
    if (style.fontStyle) lines.push(`  font-style: ${style.fontStyle};`);
    if (["pill", "overline"].includes(style.name))
      lines.push("  text-transform: uppercase;");
    const m = mobile[style.name];
    if (m) {
      lines.push(
        `  @media (max-width: 719px) {`,
        `    font-size: ${m.fontSize};`,
        `    line-height: ${m.lineHeight};`,
        `  }`,
      );
    }
    return `/* ${style.usage} */\n@utility type-${style.name} {\n${lines.join("\n")}\n}`;
  }),
);

const css = `/* GENERATED by scripts/build-tokens.mjs from design-system/tokens.json. Do not edit. */

:root,
[data-theme="${first}"] {
${rawVars(first).join("\n")}
}

${themes
  .slice(1)
  .map((t) => `[data-theme="${t}"] {\n${rawVars(t).join("\n")}\n}`)
  .join("\n\n")}

@theme inline {
  /* Colours: bg-brand, text-ink, border-line, … (switch with data-theme) */
${tokens.color.tokens.map((t) => `  --color-${t.name}: var(--${t.name});`).join("\n")}

  /* Shadows: shadow-sm / shadow-md / shadow-lg */
${tokens.shadow.tokens.map((t) => `  --${t.name}: var(--elev-${t.name.replace(/^shadow-/, "")});`).join("\n")}

  /* Font families: font-display, font-sans, font-serif, font-mono */
${Object.entries(tokens.type.families)
  .map(([k, v]) => `  --font-${k}: ${family(v)};`)
  .join("\n")}
}

@theme {
  /* Radius: rounded-sm / md / lg / xl / pill */
${tokens.radius.tokens.map((t) => `  --${t.name}: ${t.value};`).join("\n")}

  /* Breakpoints follow the design system: 640 / 720 / 1024 */
  --breakpoint-md: 720px;
}

/* Spacing needs no mapping: Tailwind's 4px step equals space-1…space-24 (p-6 = 24px = space-6). */

/* Type styles: className="type-h1", "type-body", "type-mono", … */
${typeUtilities.join("\n\n")}
`;

writeFileSync(out, css);
console.log(`Wrote ${out}`);
