# Generated by Django 6.1.1 on 2026-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("name", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
